baseURL = "//liveword.blog/"
languageCode = "en-us"
title = "liveword"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Words"
    url = "/words/"
    weight = 2
  [[menu.main]]
    name = "Photos"
    url = "/photos"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4
  [[menu.main]]
    name = "Sitemap"
    url = "/sitemap"
    weight = 5
